In [4]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML

from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [24]:
IMAGE_SIZE = 256
CHANNELS = 3

train_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

train_generator = train_datagen.flow_from_directory(
    'dataset/train',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse'
    
    
)

Found 1506 images belonging to 3 classes.


In [26]:
for image_batch, label_batch in train_generator:
    print(image_batch[0])
    break
    

[[[0.64434165 0.61689067 0.6482632 ]
  [0.6423935  0.6149425  0.6463151 ]
  [0.6404454  0.61299443 0.644367  ]
  ...
  [0.7725491  0.7294118  0.74509805]
  [0.7955678  0.75243056 0.76811683]
  [0.82296586 0.7798286  0.7955149 ]]

 [[0.673121   0.64567    0.67704254]
  [0.67214686 0.6446959  0.6760684 ]
  [0.67117286 0.6437219  0.6750944 ]
  ...
  [0.7725491  0.7294118  0.74509805]
  [0.79727244 0.7541352  0.76982147]
  [0.82467043 0.7815332  0.79721946]]

 [[0.6843977  0.6569467  0.68831927]
  [0.6851283  0.6576773  0.68904984]
  [0.68585885 0.65840787 0.6897804 ]
  ...
  [0.7725491  0.7294118  0.74509805]
  [0.7989771  0.75583977 0.77152604]
  [0.82637507 0.7832378  0.7989241 ]]

 ...

 [[0.6139955  0.5473288  0.5787014 ]
  [0.57181835 0.5051517  0.53652424]
  [0.5541884  0.48752168 0.51889426]
  ...
  [0.62481815 0.56207305 0.57383776]
  [0.6201913  0.5574462  0.5692109 ]
  [0.61556447 0.5528194  0.5645841 ]]

 [[0.61131686 0.5446502  0.57602274]
  [0.57060075 0.5039341  0.53530663]


In [28]:
validation_datagen = ImageDataGenerator(
rescale=1./255,
rotation_range=10,
horizontal_flip=True)

validation_generator = validation_datagen. flow_from_directory(
'dataset/val',
target_size=(IMAGE_SIZE,IMAGE_SIZE),
batch_size=32,
class_mode="sparse"

)

Found 215 images belonging to 3 classes.


In [30]:
test_datagen = ImageDataGenerator(
rescale=1./255,
rotation_range=10,
horizontal_flip=True)

test_generator = test_datagen. flow_from_directory(
'dataset/test',
target_size=(IMAGE_SIZE,IMAGE_SIZE),
batch_size=32,
class_mode="sparse"

)

Found 431 images belonging to 3 classes.


In [76]:
from tensorflow.keras import models, layers

IMAGE_SIZE = 256  # or your desired image size
CHANNELS = 3
n_classes = 3

model = models.Sequential([
    layers.Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Save the model in the recommended format
model.save("/tmp/potatoes.keras")


In [78]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Layer (type)             ┃ Output Shape      ┃   Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ conv2d_18 (Conv2D)       │ (None, 254, 254,  │       896 │
│                          │ 32)               │           │
├──────────────────────────┼───────────────────┼───────────┤
│ max_pooling2d_18         │ (None, 127, 127,  │         0 │
│ (MaxPooling2D)           │ 32)               │           │
├──────────────────────────┼───────────────────┼───────────┤
│ conv2d_19 (Conv2D)       │ (None, 125, 125,  │    18,496 │
│                          │ 64)               │           │
├──────────────────────────┼───────────────────┼───────────┤
│ max_pooling2d_19         │ (None, 62, 62,    │         0 │
│ (MaxPooling2D)           │ 64)               │           │
├──────────────────────────┼───────────────────┼───────────┤
│ conv2d_20 (Conv2D)       │ (None, 60, 60,    │    36,928 │
│                          │ 64)               │           │
├──────────────────────────┼───────────────────┼───────────┤
│ max_pooling2d_20         │ (None, 30, 30,    │         0 │
│ (MaxPooling2D)           │ 64)               │           │
├──────────────────────────┼───────────────────┼───────────┤
│ conv2d_21 (Conv2D)       │ (None, 28, 28,    │    36,928 │
│                          │ 64)               │           │
├──────────────────────────┼───────────────────┼───────────┤
│ max_pooling2d_21         │ (None, 14, 14,    │         0 │
│ (MaxPooling2D)           │ 64)               │           │
├──────────────────────────┼───────────────────┼───────────┤
│ conv2d_22 (Conv2D)       │ (None, 12, 12,    │    36,928 │
│                          │ 64)               │           │
├──────────────────────────┼───────────────────┼───────────┤
│ max_pooling2d_22         │ (None, 6, 6, 64)  │         0 │
│ (MaxPooling2D)           │                   │           │
├──────────────────────────┼───────────────────┼───────────┤
│ conv2d_23 (Conv2D)       │ (None, 4, 4, 64)  │    36,928 │
├──────────────────────────┼───────────────────┼───────────┤
│ max_pooling2d_23         │ (None, 2, 2, 64)  │         0 │
│ (MaxPooling2D)           │                   │           │
├──────────────────────────┼───────────────────┼───────────┤
│ flatten_3 (Flatten)      │ (None, 256)       │         0 │
├──────────────────────────┼───────────────────┼───────────┤
│ dense_6 (Dense)          │ (None, 64)        │    16,448 │
├──────────────────────────┼───────────────────┼───────────┤
│ dense_7 (Dense)          │ (None, 3)         │       195 │
└──────────────────────────┴───────────────────┴───────────┘

 Total params: 183,747 (717.76 KB)

 Trainable params: 183,747 (717.76 KB)

 Non-trainable params: 0 (0.00 B)

In [48]:
model.compile(
optimizer='adam',
loss=tf.keras. losses. SparseCategoricalCrossentropy(from_logits=False),
metrics=['accuracy']
)

In [80]:
model.fit(
    train_generator,
    steps_per_epoch=47,
    batch_size=32,
    validation_data=validation_generator,
    validation_steps=6,
    verbose=1,
    epochs=20
)


Epoch 1/20


ValueError: Arguments `target` and `output` must have the same rank (ndim). Received: target.shape=(None,), output.shape=(None, 3)

In [60]:
model.save("../potatoes.h5")

In [62]:
model.save("../potatoes.keras")


In [68]:

model.save("../potatoes2.keras")  

In [72]:
pip install tensorflow==2.5.0


Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.0 (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0)
ERROR: No matching distribution found for tensorflow==2.5.0
